const triviaData = {
    "Incredibles 2": [
      "Evelyn Deavor's name is a pun on 'evil endeavor,' foreshadowing her villainous side.",
      "This was Pixar's fourth follow-up film where the protagonist and side character switch roles, with Mrs. Incredible/Elastigirl taking on the role of the protagonist from Mr. Incredible.",
      "The fourteen-year gap between the first film and this follow-up was the longest waiting time between a Disney/Pixar movie and its follow-up.",
      "As of 2017, this movie holds the record for the most viewed animated teaser trailer of all time, with one hundred thirteen million views in the opening week.",
      "When Mr. Incredible is drinking coffee while learning Dash's math homework, he uses an Insuricare coffee mug, the company for which he worked in The Incredibles (2004).",
      "This was Pixar's fourth film to have a female protagonist, after Brave (2012), Inside Out (2015), and Finding Dory (2016).",
      "Just before Evelyn Deavor is revealed as the villain, she modifies her voice while drinking, hinting at her alter ego, Screenslaver.",
      "Winston says he bought his house from an eccentric billionaire, resembling Tony Stark's Malibu home in Iron Man (2008).",
      "A government device with a red beam of light erases memories, similar to the Neuralyzer used in Men in Black (1997).",
      "Frozone's wife Honey does not appear on-screen, only heard yelling at him off camera.",
      "Jack-Jack has seventeen superpowers, the most for any superhero in the movie."
    ],
    "Toy Story 4": [
      "When Bo Peep gets taken away, the car driven by the new owner has the license plate RMRF97, referencing a near loss of Toy Story 2.",
      "Duke Caboom first appeared in Jack-Jack's crib in Incredibles 2 (2018).",
      "Bing Bong's rocket from Inside Out (2015) and Ellie and Carl's house from Up (2009) can be seen in an antique shop.",
      "Tom Hanks, Tim Allen, Wallace Shawn, John Ratzenberger, Debi Derryberry/Jeff Pidgeon, and Frank Welker are the only cast members to appear in all four Toy Story films.",
      "Each successive Toy Story film is 11 minutes longer than its predecessor, except for the fourth film.",
      "Toy Story 4 is the only film in the franchise that does not have a villain.",
      "Remains the only Toy Story film that doesn't feature or mention the Green Army Men.",
      "When Duke does his big jump at the end, he does it with his eyes closed, referencing Buzz's attempt to fly.",
      "This is the third Toy Story film where a main character loses an arm.",
      "When Duke hypes himself up, the Canadian national anthem 'O Canada' can be heard, likely a nod to his voice actor Keanu Reeves.",
      "This is Pixar's first film to win the Academy Award for Best Animated Feature since Coco (2017)."
    ],
    "Toy Story 3": [
      "There are 302 characters in Toy Story 3, the most of any Pixar film.",
      "Rex gets his wish for a new dinosaur in Toy Story 3 when Bonnie has Trixie.",
      "Mr. Potato Head was originally just a set of eyeballs and hands for real vegetables.",
      "Andy's bedroom door has a sign that says 'Newt Xing,' referencing a canceled Pixar film.",
      "Big Baby is based on a doll owned by Lee Unkrich's daughter.",
      "Andy's calendar features Snot Rod from Cars (2006).",
      "When Ms. Davis parks at Sunnyside Daycare, you can see Van from Cars next to her car.",
      "The sanitation worker in the film is Sid, now all grown up.",
      "Set approximately 10 years after Toy Story 2.",
      "First sequel to win the Academy Award for Best Animated Feature.",
      "The first Toy Story film without a human antagonist, though Sid briefly appears."
    ],
    "Finding Dory": [
      "Dory is the most liked character on Facebook from any Disney or Pixar film.",
      "The license plate on the truck is CALA113, referencing Cal Arts.",
      "Characters from other Pixar films make cameos as visitors to the Marine Institute.",
      "The Pizza Planet truck appears in a wrecked state in the film.",
      "Ellen DeGeneres revealed the first trailer for Finding Dory on her show.",
      "Most characters in this movie have a handicap or disability.",
      "Finding Dory became the highest grossing animated film in American box office history.",
      "Features fewer characters without American accents than Finding Nemo.",
      "Dory talks in her sleep, referencing Fix-It Felix.",
      "One of the tanks says 2015, referencing the film's release date.",
      "Hank is the third Pixar character with camouflage ability."
    ],
    "Kung Fu Panda": [
      "The character Po was inspired by a panda that was raised in a zoo in China.",
      "Jackie Chan was originally approached to voice Po but declined the role.",
      "The film's animation team studied real martial arts experts to create realistic fight scenes.",
      "The movie was nominated for an Academy Award for Best Animated Feature.",
      "Po's father, Mr. Ping, is a goose, while Po is a panda, highlighting the film's themes of family and identity.",
      "The animators took a six-hour kung fu class to get an idea of the movie's action.",
      "This movie took four years to make.",
      "The film was originally going to be a spoof of the Kung Fu genre, but one of the directors, John Stevenson, wanted to have a blend of comedy and action to make this movie more epic, saying, 'I wasn't interested in making fun of martial arts movies, because I really think they can be great films. They can be as good as any genre movie when they're done properly.'",
      "The name of the prison is 'Chor Ghom Prison'. 'Chor Ghom' is Cantonese for 'go to prison' or to literally 'sit in prison'.",
      "The Kung Fu and Wuxia convention, where attacks on the correct nerve and Chi points can cause paralysis and other effects, is adopted, although it is not explained in the movie, and the jade figurine topped sticks on the shell worn on the imprisoned Tai Lung are positioned at the traditional Chi energy points of the body. The sticks are intended to keep the villain from accessing the power from those points, which is why he was first concerned about removing them before attempting to break his chains",
      "Pressure points are more difficult to locate on obese people, as shown when Mantis has trouble performing acupuncture on Po. In the end, this served to protect Po from Tai Lung's pressure point attacks.",
      "When the rope bridge fight scene was conceived by directors Mark Osborne and John Stephenson, the animators protested that they didn't know how to create such a complex sequence. For the directors, that protest was an encouraging sign. It meant that nothing like it had been done before, and thus they were determined to create it.",
      "The main enemy in Po's dream (at the beginning) turned out to be Kai, the main villain in Kung Fu Panda 3 (2016), and the wolves turned out to be the Wolf Army from Kung Fu Panda 2 (2011).",
      "Jack Black was nearly forty-years-old when he voiced the young Po.",
    ],
    "Frozen": [
      "The song 'Let It Go' won the Academy Award for Best Original Song in 2014.",
      "Elsa was originally intended to be the villain of the story.",
      "The film was inspired by Hans Christian Andersen's fairy tale 'The Snow Queen.'",
      "Frozen became the highest-grossing animated film at the time of its release.",
      "The character Olaf was originally going to be a villain.",
      "When the gates open during 'For The First Time in Forever,' there is a cameo of Rapunzel and Eugene (Flynn) from Tangled (2010). Rapunzel has short, brown hair and is wearing a purple and pink dress (her celebration dress at the end of 'Tangled'), and Eugene is wearing a maroon vest and a brownish sash. They are entering the screen from the left.",
      "Originally, Queen Elsa was intended to be the villain of the story. However, when the character's major song, 'Let It Go,' was played for the producers, they concluded that the song was not only very appealing, but its themes of personal empowerment and self-acceptance were too positive for a villain to express. Thus, the story was rewritten to have Elsa as an isolated innocent who is alarmed upon learning that her powers are inadvertently causing harm and struggles to control her powers with Anna's help.",
      "Idina Menzel auditioned for the part of Rapunzel in Disney's previous fairy tale, Tangled (2010). Even though Menzel didn't get the part, a Disney casting director recorded her audition, and two years later, it got her the part of Elsa.",
      "According to actor Josh Gad, a handful of Olaf's dialogue in the film was improvised to make the producers laugh.",
      "A live reindeer was brought into the animating studio for animators to study its movements and mannerisms for the reindeer character, Sven. Co-director Jennifer Lee said it was the best moment during production for her.",
      "Elsa is the second animated Disney princess to become a Queen during a film and the first animated Disney princess to be crowned Queen on-screen. (Princess Kida from Atlantis: The Lost Empire (2001) was first, but her coronation happens off-screen.)",
      "Upon winning the Golden Globe Award for Best Animated Feature Film, Frozen (2013) became the first full-length Disney (non-Pixar) animated feature to win this award, after four previous nominations. Frozen is also the first Disney animated feature film to win a Golden Globe since Tarzan (1999), also directed by Chris Buck.",
      "Surpassed Toy Story 3 (2010) as the highest-grossing animated film, and itself held the record until surpassed by The Lion King (2019).",
      "Elsa's ice castle changes color with her emotions. Blue is happy, red is fear, and yellow is anger.",
    ],
    "How to Train Your Dragon": [
      "The film was based on the book series by Cressida Cowell.",
      "Toothless, the dragon, was designed to be a mix between a cat and a dragon.",
      "The film's animators studied the movements of real animals to create realistic dragon behavior.",
      "How to Train Your Dragon won several awards, including the Academy Award nomination for Best Animated Feature.",
      "The franchise includes two sequels and a TV series.",
      "The hesitation Toothless shows during the famous 'touch' scene was actually an animation error. However, it looked so perfect that the animators chose to leave it in the film.",
      "In the book of 'How to Train Your Dragon,' Hiccup does not have a love interest. Furthermore, Toothless, the dragon in the book, is about the size of the Terrible Terror breed, and he is also green and red, not black. Toothless also got his name because when Hiccup first found him, he had no teeth. He grew one tooth, only to lose it shortly later. The producers decided, with the approval of author Cressida Cowell, that it would be more cinematic to make Toothless large enough to be ridden as a flying mount. As such, Toothless was completely redesigned as a rare Night Fury, a highly intelligent breed of dragon evolved for speed and stealth. His personal name, in the film, derives from Hiccup's observation about how his teeth are normally retracted into his jaws so they don't interfere with his fire breathing, which is typically projected as an explosive pulse.",
      "During the popular DreamWorks intro part of the movie, where a boy on the crescent moon is holding a fishing pole, the shadow of the Night Fury flying through the star-filled background can be seen for a brief moment",
      "According to the audio commentary, when Hiccup, Astrid and Toothless are flying to Dragon Island and are surrounded by all the other dragons, one of the dragons is carrying Gloria, the hippo from Madagascar (2005).",
      "The appearance and personality of Toothless was inspired by cats, dogs, and horses. The face also bears some resemblance to the giant salamander, the largest amphibian in the world. The shape of his face is also reported to have been based on the face of Stitch from Lilo & Stitch (2002), also directed by Chris Sanders and Dean DeBlois. Sanders and DeBlois used to work for Walt Disney Pictures as studio members until 2007 when they joined DreamWorks Animation to work on most films starting with Kung Fu Panda (2008).",
      "The character Stoick is 7'2' tall.",
      "Hiccup is the only character to refer to Toothless by name.",
      "Hiccup's exact age is never given in the film. However, in How to Train Your Dragon 2 (2014), which takes place five years after How to Train Your Dragon (2010), Hiccup is said to be 20 years old. This would make him 15 years old in this film.",
      "When the vikings celebrate, after all of the dragons fly out of the volcano, nearly all of them are holding their swords left-handed.",
      "The hammer used by Stoick bears a strong resemblance to the Marvel comics version of the hammer Mjolnir, wielded by Marvel's Thor. The traditional mythological hammer of Thor looks much different.",
      "The hammer used by Stoick bears a strong resemblance to the Marvel comics version of the hammer Mjolnir, wielded by Marvel's Thor. The traditional mythological hammer of Thor looks much different.",
    ],
    "Spider-Man: Into the Spider-Verse": [
      "The film features over 140 characters, with 40 of them being unique Spider-People.",
      "It was the first animated film to win the Academy Award for Best Animated Feature under the new category.",
      "The animation style combines traditional 2D comic book art with 3D animation.",
      "Shameik Moore, who voices Miles Morales, also contributed to the film's soundtrack.",
      "The film was praised for its representation of a diverse cast of characters.",
      "Completing the animation for the film required up to 180 animators, the largest crew ever used by Sony Pictures Animation for a film",
      "Phil Lord and Christopher Miller had a goal for the movie, 'Inspire young people to become heroes, inspire grown-ups to help them do it, and remind us all that you don't need to be bitten by a radioactive spider to do your part. You are powerful, and we are counting on you.'",
      "(at around 52 mins) The 'bagel' text as the bagel hits the scientist's head was a joke pitch that an animator took seriously and added in. They loved it.",
      "(at around 3 mins) Upon closer attention, Miles Morales can be seen doing to one of his friends the long handshake Peter Parker and Ned Leeds do in Spider-Man: Homecoming (2017) when he walks to school.",
      "Amongst all of the alternate Spider-Man suits in the deceased Spider-Man's underground lair are the Iron Spider suit from the 'Civil War' comic arc and the suit from the Sony's PlayStation 4 game with the white spider detail.",
      "Originally, Peni was going to die along with SP//DR, but this was deemed too brutal for a 'kids movie,' so she survived the destruction of her mech.",
      "(at around 1h 6 mins) When Jefferson scrolls through his phone contacts, 'Steve Ditko' is shown as one of the contacts. This is a reference to Steve Ditko, one of the original creators of 'Spider-Man' and one of the two men the film is dedicated to.",
      "In addition to the usual Spider-Man powers, Spider-Ham is able to throw a black circle on a wall and climb through it. This is an idea first used in the Warner Bros. cartoon The Hole Idea (1955).",
      "Keep your eye out for Stan Lee's character. In addition to Miles visiting his store, Lee can be seen about town throughout the film, such as when Miles and Peter B. land in the crosswalk.",
      "(at around 1h 30 mins) Spider-Ham's final line, 'That's all, folks!' is the tagline of Porky Pig for ending Looney Tunes cartoons (except he says it with his characteristic stutter). Spider-Ham never removes his mask, and the outline of his head and body bear a remarkable resemblance to Porky Pig.",
      "(at around 1h 40 mins) As the collider is being destroyed, Miles looks into the closing hole and sees multiple web like figures closing in on each other. This is the Web of Destiny: the Tapestry of the Universe, an extra-dimensional force that binds all the Spider-People together. Meaning that Miles is the only Spider-Person to get a glimpse of the truth of the multi-verse.",
      "(at around 17 mins) When Miles is first discovering his powers and trying to get back into his room, he loses all of his clothing except for his pants. His final 'outfit' is similar to the outfit worn by Childish Gambino, AKA Donald Glover, in his Childish Gambino: This Is America (2018) music video. Donald Glover plays Aaron Davis in Spider-Man: Homecoming (2017) and was the central focus of a petition for him to play Miles Morales in a live action Spider-man movie.",
      "The first Spider-Man film to win an Oscar since Spider-Man 2 (2004), which won an Oscar for Best Visual Effects.",
    ],
    "Zootopia": [
      "The film explores themes of prejudice and stereotypes through its anthropomorphic animal characters.",
      "Zootopia's design was inspired by real-world cities like San Francisco and Tokyo.",
      "The character Judy Hopps is the first rabbit police officer in the city of Zootopia.",
      "The film won the Academy Award for Best Animated Feature in 2017.",
      "Zootopia's creative team visited several zoos to study animal behavior and habitats.",
      "Originally, the film revolved around Nick Wilde. Test audiences said that they had a hard time connecting with him emotionally, and found themselves drawn to Judy Hopps, so the story was changed.",
      "Nick Wilde's design is heavily based on the title character of Disney's Robin Hood (1973) (who is also a fox).",
      "Animators decided upon Judy's purple eye color because they thought the rest of her gray fur markings were too dull, particularly for a main character. Purple was chosen to represent her energetic and optimistic personality.",
      "On her train ride to Zootopia, before Judy selects Gazelle, some of the other artists on her music player include: The Beagles, Black Sable, Catty Perry, Destiny's Cub, Ewe 2, Fleetwood Yak, Fur Fighters, Gun N' Rodents, Hyena Gomez, Kanine West and Mick Jaguar. These are references to the bands and singers, Destiny's Child, The Beatles, Black Sabbath, Katy Perry, Fleetwood Mac, Guns N' Roses, Selena Gomez, Ye, U2, Mick Jagger, and Foo Fighters.",
      "There are no reptiles, birds, fish, or amphibians throughout the entire movie; instead, there are only mammals and occasional flies. This was in keeping with the Prey and Predator theme of the film.",
      "The nudist Indian Yoga instructor is named Nangi. Nangi refers to a naked woman in the Hindi language.",
      "Chief Bogo's name is taken from the Swahili word 'mbogo,' meaning buffalo.",
      "When interrogated Nick said he had been doing this 'since he was 12.' While Judy is multiplying everything together to figure out how much he owes in taxes, we hear her say 'times two decades.' That would make Nick 32.",
      "Nick calls Judy Hopps by her first name only once in the film, and it's after the scene where they flush themselves from a toilet. He more commonly calls her 'Rabbit', 'Carrots' or 'Fluff'. The fact he calls her by her first name when he is most frantic about her safety after falling into the water below marks his true feelings for her.",
    ],
    "Big Hero 6": [
      "The film is loosely based on the Marvel comic of the same name.",
      "Baymax, the inflatable healthcare companion, was inspired by the concept of a health care worker.",
      "Big Hero 6 won the Academy Award for Best Animated Feature in 2015.",
      "The film features a mix of Eastern and Western animation styles.",
      "The character design for Baymax was influenced by the idea of a 'cuddle buddy.'",
      "According to Scott Watanabe, the movie is set in an alternate future where after the 1906 earthquake, San Francisco was rebuilt by Japanese immigrants using techniques that allow movement and flexibility in a seismic event. After the city was finished being rebuilt, it was renamed San Fransokyo due to it being a city with Japanese and American architecture combined.",
      "Baymax's movement and posing was modeled after studying the movement of a baby with a full diaper.",
      "When Baymax first tests out his new rocket fist in Fred's mansion, the statue that it destroys is a statue of Hans from Frozen (2013).",
      "The production team watched videos of fire ants as an inspiration of the movement of the Microbots.",
      "In Hiro's room, next to his computer monitor, there appears to be a robot head resembling E.V.E. from WALL·E (2008).",
      "In Fred's library/museum, one of the small statuettes in the background book case is Elastigirl from The Incredibles (2004).",
      "The design of Baymax's eyes was taken from a Japanese traditional bell, which is called Suzu. Don Hall, the director, says that he got the inspiration when he visited a temple in Japan.",
      "When Hiro falls between his desk and bed after activating Baymax, you can see Oswald the Lucky Rabbit's face on Hiro's ceiling. Oswald was Walt Disney's first animated character before Mickey Mouse.",
      "This is the first Disney film to only show the title of the movie at the end and not the beginning.",
      "Although being made by Disney, the characters in the film are from Marvel Comics",
      "Hans from Frozen (2013) can be seen on the most wanted board at the police station.",
      "In the first scene in the college lab, each one of the main characters are working on something that helps them in the battles in this movie. Gogo is making a speedy bike which later is added to her suit to make her faster, Wasabi is working on lasers which get turned into his arm blades, Honey is working on chemical orbs which later become her main weapon, and Fred shows his sign spinning which aides him in the final battle.",
    ],
    "The Mitchells vs. The Machines": [
      "The film was originally titled 'Connected' before its release on Netflix.",
      "It features a unique animation style that combines 2D and 3D techniques.",
      "The movie addresses themes of family dynamics and technology's impact on relationships.",
      "The character of Katie Mitchell was inspired by director Mike Rianda's own experiences growing up.",
      "This film received critical acclaim for its humor and heartwarming story",
      "This is the first Sony Pictures Animation film to feature an LGBT character.",
      "Originally titled 'The Mitchells vs. the Machines' then changed to 'Connected', but once it was purchased by Netflix the title reverted back to 'The Mitchells vs. the Machines'.",
      "When Katie and her father are fighting the robots while dancing to their song, a freeze shows them as the Dream Team. The whoosh that follows this freeze contains a letter from Katie to all creative kids asking kids not to stop being creative even if you aren't good at it because it's fun and you get better. Plus you get to make movies about farting.",
      "Jim and Hailey Posey, the Mitchells' neighbors, are voiced by John Legend and Chrissy Teigen, who are married in real life.",
      "PAL is possibly an homage to HAL the computer from 2001 a Space Odyssey. The robots even have a single red eye as HAL did.",
      "During PALs final moments in the glass of water, while her screen is glitching for a fraction of a second a live action picture of a man wearing a blue shirt eating a slice of pizza flashes across her screen.",
      "Aaron was originally going to be voiced by an actual child actor, but eventually went to be played by the director himself.",
      "Katie and Rick's glasses do not have lenses.",
      "The movie was completed on September 24th 2020.",
      "The directors put in the world's biggest Furby because they thought it would be funny, not realizing that such a thing actually exists.",
      "Due to the Covid-19 pandemic, Sony sold the rights to the film to Netflix. One of the first things the streaming platform did was to reinstate director Michael Rianda's preferred title, The Mitchells vs the Machines (2021).",
      "The socks Katie wears has the same pattern as the carpet in The Overlook Hotel from The Shining.",
    ],
    "SHREK": [
      "The principal actors never met each other. They all read their parts separately, with a reader feeding them the lines. John Lithgow later admitted that, while he enjoyed playing Lord Farquaad, he was a little disappointed that he never actually worked directly with Mike Myers, Cameron Diaz, or Eddie Murphy.",
      "Shrek received his own star on the Hollywood Walk of Fame.",
      "The scene where Princess Fiona burps was written after a recording session where Cameron Diaz burped after drinking Coca-Cola. Eddie Murphy improvised Donkey's response to Shrek, 'She's as nasty as you are!'",
      "Mike Myers was in New York City when the crew realized that the line 'What are you doing in my swamp?!' had never been read. So producer Jeffrey Katzenberg flew to New York City and had Myers read the line in the back of a limo.",
      "'Shrek' means 'monster' in Yiddish, and is derived from the German word 'Schreck,' which means 'terror' or 'fright.'",
      "The effects department actually took mud showers to study how to realistically portray mud in the film.",
      "Steven Spielberg was originally going to produce the film in 1991, when he was in charge of Amblin Entertainment. Then, the film would have been in hand-drawn animation, and was going to star Bill Murray as Shrek and Steve Martin as Donkey.",
      "There are 36 unique locations in Shrek - more than any other computer-animated film at the time.",
      "Donkey and Fiona are the only characters to refer to Shrek by name in this film. Others would later do so in the other films.",
      "In an interview once Eddie Murphy joked that the movie Shrek, and his character Donkey, became so popular that if he had died the year the movie was released,newspapers would have probably used a picture of Donkey instead of Eddie Murphy.",
      "Mike Myers was hesitant about succeeding the role of Shrek from Chris Farley, due to them being friends and believing it was disrespectful to do so. But after thinking it over and the producers all telling Myers: 'Can't we just settle this over a pint?,' he decided to take on the role. And that line was eventually used in the final cut of the film",
      "Over 1,000 fantasy characters invade Shrek's swamp at the beginning of the movie.",
      "Everything in Farquaad's castle is designed to be angular (no curves or bends) to heighten his evil nature.",
      "The whole animation team from Antz (1998), DreamWorks' first animated movie, were recruited to work on Shrek.",
      "Lord Farquaad uses the lowercase 'F' ('small' f) as his flag. This is a reflection of his small stature.",
      "DreamWorks punished animators who failed on The Prince of Egypt by sending them to work on this film. They even called it 'To Get Shreked.'",
    ],
    "Spiderman Across The Spider Verse" : [

      "The sequence on Earth-13122, the Lego universe, was animated by 14-year-old Preston Mutanga, who was hired after Phil Lord and Christopher Miller were impressed with his Twitter video recreating the entire trailer with Lego.",
      "Miles is sent by the Go-Home Machine to his 'home' universe, Earth 42. The number 42 is prominent throughout Miles' life such as the lottery number that won him the money to go to Vision Academy, the spider's number, the train station where Miles is chased by the Prowler, etc.",
      "When Miles is shown Uncle Ben and Captain Stacy's deaths from the Tobey Maguire, Andrew Garfield and Spectacular Spider-Man universes, they show clips from Spider-Man (2002), Intervention (2008), and The Amazing Spider-Man (2012), but for Uncle Ben's death in Andrew Garfield's universe, they use a clip from the video game version of The Amazing Spider-Man 2 (2014).",
      "Grossed over $1 million domestically every day for 45 consecutive days, the most of any Spider-Man film, tied with Spider-Man (2002).",
      "On Earth-42, buildings in the background have members of that universes Sinister Six on them, Electro, Rhino, Vulture, Scorpion, Shocker, Sandman",
      "The film's main poster itself is foreshadowing: those who will remain loyal to Miguel are on the left while those who will rebel to join Miles are on the right.",
      "Earth-65, the home of Gwen Stacy, was designed to look like 'impressionistic' watercolor paintings. The animation team created a simulator to generate this style and used a visual palette that reflects Gwen's emotions like a 'three dimensional mood ring'.",
      "The fifth Sony film nominated for the Academy Award for Best Animated Feature, after Surf's Up (2007), Pirates! (2012), Spider-Man: Into the Spider-Verse (2018), and The Mitchells vs the Machines (2021). Only Into the Spider-Verse has won.",

    ],
    "Finding Nemo" : [

    "Pixar's characters are often planned years in advance. Nemo first appeared as a stuffed toy on a couch in Boo's room in Monsters, Inc. (2001). This movie introduces the main characters of post-2003 Pixar films. A boy in the dentist's office is reading a 'Mr. Incredible' comic book, anticipating The Incredibles (2004). Luigi the car is driving by the dentist's office, anticipating Cars (2006).",
    "Filmmakers were worried that comedian Ellen DeGeneres would not be able to perform the dramatic scene where Dory begs Marlin not to leave, so at the end of a day of recording other scenes, they asked her to record a trial reading of the scene, with the intention that she go home with a recording of it to work on her actual performance. DeGeneres agreed, but her trial reading was so heartfelt and emotional that (apart from a few small edits) this is what was used in the final cut of the film",
    "SERIES TRADEMARK: When Gil thinks about how he and the fish will escape, as the camera pans toward and out the window, the Pizza Planet truck from Toy Story (1995) can be seen outside. This is the first film where the truck has a distinctive appearance, being a right-handed vehicle driving on the left side of the road since it's in Sydney, Australia.",
    "In Latin, the word nemo means 'nobody' or 'no one.' It is also a reference to Captain Nemo in Jules Verne's novel '20,000 Leagues Under the Sea.'",
    "SERIES TRADEMARK: Among the toys in the waiting room are the jack-in-the-box and Buzz Lightyear and, on a shelf, the plane he used to 'fly' in Toy Story (1995) and Pixar's trademark ball from Luxo Jr. (1986).",
    "First animated film from Disney to win the Academy Award for Best Animated Feature.",
    "There are up to 200 turtles in the background of the turtle drive sequence",
    "Most of the fish are actual saltwater fish that can be found in the Pacific Ocean. Nemo is a clownfish (so is Marlin), Dory is a Regal Blue Tang, Gil is a Moorish Idol, Bloat is a Porcupinefish, Bubbles is a Yellow Tang, Peach is an Ochre Starfish, Gurgle is a Royal Gramma, Jacques is a Cleaner Shrimp, and Deb is a Damsel Fish.",
    "Dory never says Marlin's name in the whole movie despite being with him throughout most of the film.",
    "Ellen DeGeneres loved playing Dory so much that she was constantly asking Pixar to make a sequel, which they eventually did with Finding Dory (2016)",
    "The first Pixar movie to have a post-credits scene.",
    "The submarine that the sharks take Marlin and Dory to is an American Gato-class World War II-era submarine. The Submarine is USS Flier (SS-250) which was sunk by a mine on a war patrol out of Brisbane.",
    "This is the first Disney Pixar film to not be released in November.",
    ],
    "Moana" :[
        "Dwayne Johnson believes that voice acting is the most difficult career in acting, and is personally annoyed when celebrities are cast in animated films despite voicing their characters badly. When Johnson was cast for the film, he repeatedly asked the other voice actors present if he was really giving a good performance.",
        "Actor Trademark (Dwayne Johnson): When Moana first meets Maui, he cocks his eyebrow in a strange way. This is the people's eyebrow, Johnson's signature move from his wrestling career.",
        "When he first gets his hook and is trying to shapeshift, Maui changes into various animals. For a split second, he turns into Sven the Reindeer from Frozen (2013).",
        "The genie's lamp from Aladdin (1992) can be seen on Tamatoa's shell.",
        "In the trailer, Maui says he captured the sun with a fish hook and pulled the land from the ocean. According to Maori legend, Maui pulled one of the Islands of New Zealand from the ocean while fishing, and captured the sun because the days were too short. Another version says that Maui captured the sun with a net.",
        "Moana was featured in Zootopia (2016) as a film called 'Meowana'.",
        "The tattoos on Chief Tui's abdomen are the same tattoos worn by pro wrestler Peter Fanene Maivia, Dwayne Johnson's maternal grandfather.",
        "No other human characters meet Maui except Moana.",
        "As Maui jumps into the Realm of Monsters, he shouts 'Cheehoo!' It's the 'Samoan Holler', an expression of excitement rooted in Samoa, and often said in Hawaii. It's the first Disney animated film to use a Samoan Holler.",
        "In Maui's song, 'You're welcome,' he picks a coconut and rolls it down his arm and uses his elbow to flip it up to Moana, the same way Aladdin does with an apple for Jasmine in Aladdin (1992).",
        "In the post credit scene, Tamatoa the Giant Crab broke the fourth wall, where he asked the audience if they would be happy to help him to get him out of his shell if he was named Sebastian and had a 'cool Jamaican accent'. He was making a reference to Sebastian the crab from The Little Mermaid (1989), which was also directed by John Musker and Ron Clements.",
        "Maui says to Moana, 'If you wear a dress, and have an animal sidekick, you're a princess.' It's common for the heroine of a Disney story.",
        "Starting in December 2014, Disney hosted a global casting call for the role of Moana. Thousands of girls auditioned for the role through the Internet and real-life casting calls in different locations.",
        "Towards the end, Moana gently presses her forehead against Te Ka, and then she does the same with the newly restored Te Fiti. This is a traditional Maori greeting and signifies mutual respect.",
        "When Moana goes into the sea as a young child, the waves part and become a wall of water. A giant turtle swims by, followed by a baby turtle that resembles Crush from Finding Nemo (2003) and Finding Dory (2016).",
        "HIDDEN MICKEY: Three rocks in Tamatoa's lair make the shape of Mickey's face.",
        "Moana is the first Disney Princess to have her name in the title since Mulan (1998).",
    ]
  };
  
export default triviaData;
